---
- name: Ensure parameters
  sysctl:
    name: '{{ item.name }}'
    value: '{{ item.value }}'
    state: '{{ item.state | default(omit) }}'
    sysctl_file: '{% if ansible_os_family == "RedHat" and ansible_distribution_major_version|int > 6 %}{{ kernel_parameter_config_file_path }}/{{ kernel_parameters.filename | default(kernel_parameter_config_file_name) }}{% else %}{{ kernel_parameter_config_file_path }}/{{ kernel_parameter_config_file_name }}{% endif %}'
  ignore_errors: true
  with_items: '{{ kernel_parameters.parameters }}'
